// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biozjvtnbqjbqmroebah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpb3pqdnRuYnFqYnFtcm9lYmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTM4NTAsImV4cCI6MjA1ODg2OTg1MH0.X7GNowdhyY5cvIlc8NKAEwQqvJ-txE2LxS6tQVQOmyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);